- cmd:
  - source activate submit
  - whereis python
  - echo $CUDA_VISIBLE_DEVICES
  - sleep 10
  - echo 1
  min_gpus: 1
  min_gpu_memory: 1000
  priority: 0
  available_gpu_ids: [2]
  stderr_log_path: stderr.log
  stdout_log_path: stdout.log

- cmd:
  - source activate submit
  - whereis python
  - echo $CUDA_VISIBLE_DEVICES
  - sleep 10
  - echo 2
  min_gpus: 3
  min_gpu_memory: 1000
  priority: 0

- cmd:
  - source activate submit
  - whereis python
  - echo $CUDA_VISIBLE_DEVICES
  - sleep 10
  - echo 3
  min_gpus: 3
  min_gpu_memory: 1000
  priority: 2

- cmd:
  - source activate submit
  - whereis python
  - echo $CUDA_VISIBLE_DEVICES
  - sleep 10
  - echo 3
  min_gpus: 3
  min_gpu_memory: 1000
  priority: 2
  stderr_log_path: ./log/main stderr.log
  stdout_log_path: ./log/main stdout.log

- cmd:
    - export PATH=/PATH/TO/anaconda3/bin:$PATH
    - whereis activate
  min_gpus: 0
  stdout_log_path: ./log/stdout.log
  stderr_log_path: ./log/stderr.log
    